import Database from 'better-sqlite3';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { CompRecord } from '@cre/contracts';

/**
 * The CMBS comp store — structured corpus of CompRecords parsed from EX-102
 * filings (one row per property, keyed by CIK + asset#). SQLite, mirroring the
 * cre.db convention: the .db + raw blobs are gitignored (regenerated by this
 * committed code + the recon manifest); the schema/persist logic IS the recipe.
 *
 * Same-building-across-deals (pari-passu) stays as SEPARATE rows, flagged via
 * `propertyKey` (normalized name+address) — NOT a dedup trigger. Dedup is on
 * (CIK, asset#) only — idempotency for re-runs / accidental double-ingest.
 */

const SCHEMA = `
CREATE TABLE IF NOT EXISTS comps (
  cik TEXT NOT NULL, assetNumber TEXT NOT NULL,
  dealName TEXT, accession TEXT, shelf TEXT, filingDate TEXT,
  rawBlobHash TEXT, ingestedAt TEXT,
  propertyName TEXT, address TEXT, city TEXT, state TEXT, zip TEXT, county TEXT,
  propertyType TEXT, propertyTypeCodeRaw TEXT, netRentableSF REAL, yearBuilt INTEGER,
  value REAL, valuationDate TEXT, valuationSource TEXT,
  noi REAL, ncf REAL, revenue REAL, operatingExpenses REAL, financialsDate TEXT,
  occupancyPct REAL, dscr REAL, capRate REAL,
  loanPieceAmount REAL, ltvPiece REAL, ltvReliable INTEGER,
  interestRate REAL, originationDate TEXT, originatorName TEXT,
  largestTenant TEXT, largestTenantSF REAL, largestTenantLeaseExpiry TEXT,
  propertyKey TEXT, hasValue INTEGER, fieldCoverage REAL,
  PRIMARY KEY (cik, assetNumber)
);
CREATE INDEX IF NOT EXISTS idx_comps_type ON comps(propertyType);
CREATE INDEX IF NOT EXISTS idx_comps_state ON comps(state);
CREATE INDEX IF NOT EXISTS idx_comps_propkey ON comps(propertyKey);
`;

export function openCompsStore(path: string): Database.Database {
  mkdirSync(dirname(path), { recursive: true });
  const db = new Database(path);
  db.exec(SCHEMA);
  return db;
}

/** Canonical case: first letter of each word upper, rest lower (handles "5TH"→"5th",
 *  "GENERAL SERVICES ADMINISTRATION"→"General Services Administration"). Trim+collapse. */
export function titleCase(s: string | null): string | null {
  if (s === null) return null;
  const t = s.replace(/\s+/g, ' ').trim();
  if (t.length === 0) return null;
  return t.replace(/\b[A-Za-z][A-Za-z']*\b/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());
}

const norm = (s: string | null): string | null => {
  if (s === null) return null;
  const t = s.replace(/\s+/g, ' ').trim();
  return t.length > 0 ? t : null;
};

/** Property identity for same-building detection — lowercased name+address. */
export function propertyKeyFor(name: string | null, address: string | null): string {
  return `${(name ?? '').toLowerCase().replace(/\s+/g, ' ').trim()}|${(address ?? '').toLowerCase().replace(/\s+/g, ' ').trim()}`;
}

/** Field-coverage over the 8 comp-load-bearing fields (0..1). */
const COVERAGE_FIELDS: ReadonlyArray<keyof CompRecord> = [
  'value', 'noi', 'netRentableSF', 'occupancyPct', 'dscr', 'propertyType', 'city', 'state',
];
function fieldCoverage(c: CompRecord): number {
  const present = COVERAGE_FIELDS.filter((f) => c[f] !== null && c[f] !== undefined && c[f] !== 'Other').length;
  return Math.round((present / COVERAGE_FIELDS.length) * 100) / 100;
}

/** Provenance not carried in the EX-102 itself — sourced from the recon manifest. */
export interface CompProvenance {
  readonly cik: string;
  readonly shelf: string;
  readonly rawBlobHash: string;
  readonly ingestedAt: string;
}

/** Insert one CompRecord (normalized). Returns 'inserted' or 'duplicate' (idempotent on CIK+asset#). */
export function upsertComp(db: Database.Database, c: CompRecord, prov: CompProvenance): 'inserted' | 'duplicate' {
  const stmt = db.prepare(`INSERT OR IGNORE INTO comps (
    cik, assetNumber, dealName, accession, shelf, filingDate, rawBlobHash, ingestedAt,
    propertyName, address, city, state, zip, county,
    propertyType, propertyTypeCodeRaw, netRentableSF, yearBuilt,
    value, valuationDate, valuationSource, noi, ncf, revenue, operatingExpenses, financialsDate,
    occupancyPct, dscr, capRate, loanPieceAmount, ltvPiece, ltvReliable,
    interestRate, originationDate, originatorName, largestTenant, largestTenantSF, largestTenantLeaseExpiry,
    propertyKey, hasValue, fieldCoverage
  ) VALUES (
    @cik, @assetNumber, @dealName, @accession, @shelf, @filingDate, @rawBlobHash, @ingestedAt,
    @propertyName, @address, @city, @state, @zip, @county,
    @propertyType, @propertyTypeCodeRaw, @netRentableSF, @yearBuilt,
    @value, @valuationDate, @valuationSource, @noi, @ncf, @revenue, @operatingExpenses, @financialsDate,
    @occupancyPct, @dscr, @capRate, @loanPieceAmount, @ltvPiece, @ltvReliable,
    @interestRate, @originationDate, @originatorName, @largestTenant, @largestTenantSF, @largestTenantLeaseExpiry,
    @propertyKey, @hasValue, @fieldCoverage
  )`);
  const r = stmt.run({
    cik: prov.cik,
    assetNumber: c.assetNumber ?? '?',
    dealName: c.sourceDeal, accession: c.filingAccession, shelf: prov.shelf,
    filingDate: c.filingDate, rawBlobHash: prov.rawBlobHash,
    ingestedAt: prov.ingestedAt,
    propertyName: titleCase(c.propertyName), address: norm(c.address), city: titleCase(c.city),
    state: c.state ? c.state.trim().toUpperCase() : null, zip: norm(c.zip), county: titleCase(c.county),
    propertyType: c.propertyType, propertyTypeCodeRaw: c.propertyTypeCodeRaw,
    netRentableSF: c.netRentableSF, yearBuilt: c.yearBuilt,
    value: c.value, valuationDate: c.valuationDate, valuationSource: c.valuationSource,
    noi: c.noi, ncf: c.ncf, revenue: c.revenue, operatingExpenses: c.operatingExpenses, financialsDate: c.financialsDate,
    occupancyPct: c.occupancyPct, dscr: c.dscr, capRate: c.capRate,
    loanPieceAmount: c.loanPieceAmount, ltvPiece: c.ltvPiece, ltvReliable: c.ltvReliable ? 1 : 0,
    interestRate: c.interestRate, originationDate: c.originationDate, originatorName: titleCase(c.originatorName),
    largestTenant: titleCase(c.largestTenant), largestTenantSF: c.largestTenantSF, largestTenantLeaseExpiry: c.largestTenantLeaseExpiry,
    propertyKey: propertyKeyFor(c.propertyName, c.address), hasValue: c.value !== null ? 1 : 0, fieldCoverage: fieldCoverage(c),
  });
  return r.changes > 0 ? 'inserted' : 'duplicate';
}
